// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Composable, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type { AddFilterData, AddFilterError, AddFilterResponse, CancelSubscriptionData, CancelSubscriptionError, CancelSubscriptionResponse, CreateLinkData, CreateLinkError, CreateLinkResponse, DeleteFilterData, DeleteFilterError, DeleteFilterWithTokenData, DeleteFilterWithTokenError, DoRedirectData, DoRedirectError, GetCategoriesData, GetCategoriesError, GetCategoriesResponse, GetCountryData, GetCountryError, GetCountryResponse, GetFilterByTokenData, GetFilterByTokenError, GetFilterByTokenResponse, GetFiltersData, GetFiltersError, GetFiltersResponse, GetFlipsData, GetFlipsError, GetFlipsResponse, GetInfoData, GetInfoError, GetInfoResponse, GetLinkData, GetLinkError, GetLinkResponse, GetListingData, GetListingError, GetListingResponse, GetLocationData, GetLocationError, GetLocationResponse, GetMatchesData, GetMatchesError, GetMatchesResponse, GetMeData, GetMeError, GetMeResponse, GetOptionsData, GetOptionsError, GetOptionsResponse, GetProductData, GetProductError, GetProductMatchesData, GetProductMatchesError, GetProductMatchesResponse, GetProductResponse, GetStatsData, GetStatsError, GetStatsResponse, GetSubscriptionData, GetSubscriptionError, GetSubscriptionResponse, ListLinksData, ListLinksError, ListLinksResponse, LoginFirebaseData, LoginFirebaseError, LoginFirebaseResponse, ReportMatchData, ReportMatchError, ReportMatchResponse, ReportProductIssueData, ReportProductIssueError, SearchProductsData, SearchProductsError, SearchProductsResponse, SubscribeData, SubscribeError, SubscribeResponse, TestFilterData, TestFilterError, TestFilterResponse, UpdateMeData, UpdateMeError, UpdateMeResponse, UseLinkData, UseLinkError } from './types.gen'

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const loginFirebase = <TComposable extends Composable = '$fetch', DefaultT extends LoginFirebaseResponse = LoginFirebaseResponse>(options: Options<TComposable, LoginFirebaseData, LoginFirebaseResponse, DefaultT>) => (options.client ?? client).post<TComposable, LoginFirebaseResponse | DefaultT, LoginFirebaseError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/auth/firebase',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
})

export const getFilters = <TComposable extends Composable = '$fetch', DefaultT extends GetFiltersResponse = GetFiltersResponse>(options: Options<TComposable, GetFiltersData, GetFiltersResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetFiltersResponse | DefaultT, GetFiltersError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/filters/user',
  ...options,
})

export const getOptions = <TComposable extends Composable = '$fetch', DefaultT extends GetOptionsResponse = GetOptionsResponse>(options: Options<TComposable, GetOptionsData, GetOptionsResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetOptionsResponse | DefaultT, GetOptionsError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/filters/options',
  ...options,
})

export const reportMatch = <TComposable extends Composable = '$fetch', DefaultT extends ReportMatchResponse = ReportMatchResponse>(options: Options<TComposable, ReportMatchData, ReportMatchResponse, DefaultT>) => (options.client ?? client).post<TComposable, ReportMatchResponse | DefaultT, ReportMatchError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/filters/report',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
})

export const addFilter = <TComposable extends Composable = '$fetch', DefaultT extends AddFilterResponse = AddFilterResponse>(options: Options<TComposable, AddFilterData, AddFilterResponse, DefaultT>) => (options.client ?? client).post<TComposable, AddFilterResponse | DefaultT, AddFilterError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/filters',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
})

export const deleteFilter = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, DeleteFilterData, unknown, DefaultT>) => (options.client ?? client).delete<TComposable, unknown | DefaultT, DeleteFilterError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/filters/{id}',
  ...options,
})

export const deleteFilterWithToken = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, DeleteFilterWithTokenData, unknown, DefaultT>) => (options.client ?? client).delete<TComposable, unknown | DefaultT, DeleteFilterWithTokenError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/filters/{id}/token/{token}',
  ...options,
})

export const getFilterByToken = <TComposable extends Composable = '$fetch', DefaultT extends GetFilterByTokenResponse = GetFilterByTokenResponse>(options: Options<TComposable, GetFilterByTokenData, GetFilterByTokenResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetFilterByTokenResponse | DefaultT, GetFilterByTokenError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/filters/{id}/token/{token}',
  ...options,
})

export const testFilter = <TComposable extends Composable = '$fetch', DefaultT extends TestFilterResponse = TestFilterResponse>(options: Options<TComposable, TestFilterData, TestFilterResponse, DefaultT>) => (options.client ?? client).post<TComposable, TestFilterResponse | DefaultT, TestFilterError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/filters/test',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
})

export const getLocation = <TComposable extends Composable = '$fetch', DefaultT extends GetLocationResponse = GetLocationResponse>(options: Options<TComposable, GetLocationData, GetLocationResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetLocationResponse | DefaultT, GetLocationError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/location/{zip}',
  ...options,
})

/**
 * Get the iso country code of the user
 */
export const getCountry = <TComposable extends Composable = '$fetch', DefaultT extends GetCountryResponse = GetCountryResponse>(options: Options<TComposable, GetCountryData, GetCountryResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetCountryResponse | DefaultT, GetCountryError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/country',
  ...options,
})

export const getFlips = <TComposable extends Composable = '$fetch', DefaultT extends GetFlipsResponse = GetFlipsResponse>(options: Options<TComposable, GetFlipsData, GetFlipsResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetFlipsResponse | DefaultT, GetFlipsError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/flips/{category}',
  ...options,
})

export const getMatches = <TComposable extends Composable = '$fetch', DefaultT extends GetMatchesResponse = GetMatchesResponse>(options: Options<TComposable, GetMatchesData, GetMatchesResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetMatchesResponse | DefaultT, GetMatchesError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/matches',
  ...options,
})

export const getStats = <TComposable extends Composable = '$fetch', DefaultT extends GetStatsResponse = GetStatsResponse>(options: Options<TComposable, GetStatsData, GetStatsResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetStatsResponse | DefaultT, GetStatsError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/stats',
  ...options,
})

export const getListing = <TComposable extends Composable = '$fetch', DefaultT extends GetListingResponse = GetListingResponse>(options: Options<TComposable, GetListingData, GetListingResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetListingResponse | DefaultT, GetListingError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/listing/{id}',
  ...options,
})

export const getSubscription = <TComposable extends Composable = '$fetch', DefaultT extends GetSubscriptionResponse = GetSubscriptionResponse>(options: Options<TComposable, GetSubscriptionData, GetSubscriptionResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetSubscriptionResponse | DefaultT, GetSubscriptionError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/payment/subscription',
  ...options,
})

export const subscribe = <TComposable extends Composable = '$fetch', DefaultT extends SubscribeResponse = SubscribeResponse>(options: Options<TComposable, SubscribeData, SubscribeResponse, DefaultT>) => (options.client ?? client).post<TComposable, SubscribeResponse | DefaultT, SubscribeError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/payment/subscription',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
})

export const cancelSubscription = <TComposable extends Composable = '$fetch', DefaultT extends CancelSubscriptionResponse = CancelSubscriptionResponse>(options: Options<TComposable, CancelSubscriptionData, CancelSubscriptionResponse, DefaultT>) => (options.client ?? client).delete<TComposable, CancelSubscriptionResponse | DefaultT, CancelSubscriptionError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/payment/subscription/{id}',
  ...options,
})

/**
 * Search for products by query and/or category
 */
export const searchProducts = <TComposable extends Composable = '$fetch', DefaultT extends SearchProductsResponse = SearchProductsResponse>(options: Options<TComposable, SearchProductsData, SearchProductsResponse, DefaultT>) => (options.client ?? client).get<TComposable, SearchProductsResponse | DefaultT, SearchProductsError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/Product/search',
  ...options,
})

/**
 * Get detailed information about a specific product
 */
export const getProduct = <TComposable extends Composable = '$fetch', DefaultT extends GetProductResponse = GetProductResponse>(options: Options<TComposable, GetProductData, GetProductResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetProductResponse | DefaultT, GetProductError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/Product/{id}',
  ...options,
})

/**
 * Get all listing matches for a specific product
 * Shows all available second-hand listings for price comparison
 */
export const getProductMatches = <TComposable extends Composable = '$fetch', DefaultT extends GetProductMatchesResponse = GetProductMatchesResponse>(options: Options<TComposable, GetProductMatchesData, GetProductMatchesResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetProductMatchesResponse | DefaultT, GetProductMatchesError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/Product/{id}/matches',
  ...options,
})

/**
 * Report an issue with a product (wrong categorization, incorrect info, etc.)
 */
export const reportProductIssue = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, ReportProductIssueData, unknown, DefaultT>) => (options.client ?? client).post<TComposable, unknown | DefaultT, ReportProductIssueError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/Product/{id}/report',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
})

/**
 * Get list of available product categories
 */
export const getCategories = <TComposable extends Composable = '$fetch', DefaultT extends GetCategoriesResponse = GetCategoriesResponse>(options: Options<TComposable, GetCategoriesData, GetCategoriesResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetCategoriesResponse | DefaultT, GetCategoriesError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/Product/categories',
  ...options,
})

export const doRedirect = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, DoRedirectData, unknown, DefaultT>) => (options.client ?? client).get<TComposable, unknown | DefaultT, DoRedirectError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/redirect',
  ...options,
})

export const getInfo = <TComposable extends Composable = '$fetch', DefaultT extends GetInfoResponse = GetInfoResponse>(options: Options<TComposable, GetInfoData, GetInfoResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetInfoResponse | DefaultT, GetInfoError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/referral/info',
  ...options,
})

export const createLink = <TComposable extends Composable = '$fetch', DefaultT extends CreateLinkResponse = CreateLinkResponse>(options: Options<TComposable, CreateLinkData, CreateLinkResponse, DefaultT>) => (options.client ?? client).post<TComposable, CreateLinkResponse | DefaultT, CreateLinkError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/referral/link',
  ...options,
})

export const listLinks = <TComposable extends Composable = '$fetch', DefaultT extends ListLinksResponse = ListLinksResponse>(options: Options<TComposable, ListLinksData, ListLinksResponse, DefaultT>) => (options.client ?? client).get<TComposable, ListLinksResponse | DefaultT, ListLinksError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/referral/links',
  ...options,
})

export const getLink = <TComposable extends Composable = '$fetch', DefaultT extends GetLinkResponse = GetLinkResponse>(options: Options<TComposable, GetLinkData, GetLinkResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetLinkResponse | DefaultT, GetLinkError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/referral/link/{id}',
  ...options,
})

export const useLink = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, UseLinkData, unknown, DefaultT>) => (options.client ?? client).post<TComposable, unknown | DefaultT, UseLinkError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/referral/use',
  ...options,
})

/**
 * Get current user information.
 */
export const getMe = <TComposable extends Composable = '$fetch', DefaultT extends GetMeResponse = GetMeResponse>(options: Options<TComposable, GetMeData, GetMeResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetMeResponse | DefaultT, GetMeError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/user/me',
  ...options,
})

/**
 * Update user information, allows changing name, email and locale.
 */
export const updateMe = <TComposable extends Composable = '$fetch', DefaultT extends UpdateMeResponse = UpdateMeResponse>(options: Options<TComposable, UpdateMeData, UpdateMeResponse, DefaultT>) => (options.client ?? client).post<TComposable, UpdateMeResponse | DefaultT, UpdateMeError, DefaultT>({
  security: [{ name: 'Authorization', type: 'apiKey' }],
  url: '/api/user/me',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
})
