// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://ane.coflnet.com' | (string & {});
};

export type ActiveSubscription = {
    id?: string | null;
    product?: string | null;
    createdAt?: string;
    endsAt?: string | null;
};

export type AvailabilityResult = {
    isAvailable?: boolean;
};

export type DetailedLocation = {
    lat?: number;
    lon?: number;
    name?: string | null;
    /**
     * The country code of the location, e.g., "US" for the United States.
     */
    country?: string | null;
};

export type FilterInfo = {
    name?: string | null;
    value?: string | null;
};

export type FilterMatch = {
    listenerId?: number | null;
    listingData?: StoredListing;
    matchedAt?: string | null;
};

export type FilterOptions = {
    filterType?: FilterType;
    options?: Array<StringStringKeyValuePair> | null;
};

export type FilterType = 'Options' | 'NumberRange' | 'Text' | 'Date' | 'Radius' | 'Bool' | 'MultiSelect';

export type Flip = {
    category?: string | null;
    listing?: Listing;
    serializedListing?: string | null;
    medianPrice?: number | null;
    potentialProfit?: number | null;
    serializedSells?: string | null;
    foundAt?: string | null;
    recentSells?: Array<SoldFor> | null;
};

export type InviteLink = {
    userId?: string;
    id?: string;
    name?: string | null;
    text?: string | null;
    createdAt?: string;
    expiresAt?: string;
    usageCount?: number;
};

/**
 * Types of issues that can be reported
 */
export type IssueType = 'WrongCategory' | 'Duplicate' | 'WrongListing' | 'IncorrectInformation' | 'Spam' | 'Other';

export type Listing = {
    priceKind?: PriceKind;
    platform?: Platform;
    id?: string | null;
    title?: string | null;
    descriptionShort?: string | null;
    description?: string | null;
    category?: string | null;
    street?: string | null;
    locality?: string | null;
    region?: string | null;
    country?: string | null;
    imageUrls?: Array<string> | null;
    price?: number | null;
    currency?: string | null;
    contact?: string | null;
    userId?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    shipping?: string | null;
    returnPolicy?: string | null;
    attributes?: {
        [key: string]: string;
    } | null;
    foundAt?: string | null;
    createdAt?: string | null;
    soldBefore?: string | null;
    commercial?: boolean | null;
};

export type ListingListener = {
    targetType?: TargetType;
    state?: SearchState;
    userId?: string | null;
    id?: number | null;
    filters?: Array<FilterInfo> | null;
    target?: string | null;
    name?: string | null;
    matchCount?: number | null;
};

export type MatchStats = {
    totalMatches?: number | null;
    activeSearchesLeft?: number | null;
    totalActiveSearches?: number | null;
    listenerCount?: number | null;
    listenerLimit?: number | null;
    activeRefillAmount?: number | null;
    searchesUsedMonthly?: number | null;
    searchesAvailableMonthly?: number | null;
};

export type Platform = 'Unknown' | 'Ebay' | 'Kleinanzeigen' | 'Marktplaats' | 'Willhaben' | 'Shpock' | 'MarktDe' | 'Vinted' | 'Facebook' | 'Poshmark' | 'Mercari' | 'Depop' | 'Mobile' | 'AutoScout24' | 'WirKaufenDeinAuto' | 'AutoDe' | 'Gebrauchtwagen12' | 'Craigslist' | 'OfferUp' | 'OLX' | 'Quoka' | 'Gumtree' | 'Kijiji' | 'Carousell' | 'Carvana' | 'Autotrader' | 'CarsGuide' | 'Nextdoor' | 'Lebecoin' | 'Wallapop';

export type PriceKind = 'Unknown' | 'BuyItemNow' | 'Auction' | 'Negotiatable' | 'IncludesTax';

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type Product = {
    id?: string | null;
    category?: Array<string> | null;
    name?: string | null;
    normalizedName?: string | null;
    brand?: string | null;
    model?: string | null;
    identifierType?: string | null;
    identifierValue?: string | null;
    condition?: string | null;
    averagePrice?: number;
    medianPrice?: number;
    minPrice?: number;
    maxPrice?: number;
    listingCount?: number;
    createdAt?: string;
    lastUpdated?: string;
    sampleTitles?: Array<string> | null;
    imageUrl?: string | null;
    attributes?: {
        [key: string]: string;
    } | null;
    canonicalSeoId?: string | null;
    relatedSeoIds?: Array<string> | null;
};

export type ProductAttribute = {
    key?: string | null;
    value?: string | null;
};

export type ProductDocument = {
    seoId?: string | null;
    categories?: Array<string> | null;
    name?: string | null;
    normalizedName?: string | null;
    brand?: string | null;
    model?: string | null;
    identifierType?: string | null;
    condition?: string | null;
    averagePrice?: number | null;
    medianPrice?: number | null;
    minPrice?: number | null;
    maxPrice?: number | null;
    listingCount?: number | null;
    createdAt?: string;
    lastUpdated?: string;
    attributes?: Array<ProductAttribute> | null;
    sampleTitles?: Array<string> | null;
    imageUrl?: string | null;
    canonicalSeoId?: string | null;
    relatedSeoIds?: Array<string> | null;
};

/**
 * Report for invalid categorization or other product issues
 */
export type ProductIssueReport = {
    type?: IssueType;
    /**
     * Additional details about the issue
     */
    description?: string | null;
    /**
     * Suggested correction (optional)
     */
    suggestion?: string | null;
    /**
     * User ID who reported the issue (if authenticated)
     */
    reportedBy?: string | null;
    /**
     * When the report was submitted
     */
    reportedAt?: string;
};

/**
 * Represents a listing matched to a product
 */
export type ProductMatch = {
    /**
     * Listing ID from kleinanzeigen.de
     */
    listingId?: number;
    /**
     * Product ID this listing belongs to
     */
    productId?: string | null;
    /**
     * Listing title
     */
    title?: string | null;
    /**
     * Listing price
     */
    price?: number;
    /**
     * Listing location/city
     */
    location?: string | null;
    /**
     * URL to listing image
     */
    imageUrl?: string | null;
    /**
     * URL to the actual listing on kleinanzeigen.de
     */
    listingUrl?: string | null;
    /**
     * When the listing was posted
     */
    postedAt?: string;
    /**
     * Item condition (e.g., "Neu", "Wie neu", "Gut", "Akzeptabel")
     */
    condition?: string | null;
    /**
     * Confidence score of the product match (0-1)
     */
    matchScore?: number;
};

export type ReferralInfo = {
    invitedCount?: number;
};

export type ResultReport = {
    match?: FilterMatch;
    message?: string | null;
    /**
     * Optional contact option, default to email
     */
    contact?: string | null;
};

export type SearchProductsResult = {
    products?: Array<ProductDocument> | null;
};

export type SearchState = 'None' | 'Disabled' | 'DisabledError';

export type SoldFor = {
    platform?: Platform;
    key?: string | null;
    price?: number | null;
    date?: string | null;
    id?: string | null;
};

export type StoredListing = {
    platform?: Platform;
    priceKind?: PriceKind;
    id?: string | null;
    title?: string | null;
    descriptionShort?: string | null;
    description?: string | null;
    category?: string | null;
    street?: string | null;
    locality?: string | null;
    region?: string | null;
    country?: string | null;
    imageUrls?: Array<string> | null;
    price?: number | null;
    currency?: string | null;
    contact?: string | null;
    userId?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    shipping?: string | null;
    returnPolicy?: string | null;
    attributes?: {
        [key: string]: string;
    } | null;
    foundAt?: string | null;
    createdAt?: string | null;
    soldBefore?: string | null;
    commercial?: boolean | null;
    priceKindList?: Array<PriceKind> | null;
};

export type StringStringKeyValuePair = {
    key?: string | null;
    value?: string | null;
};

export type SubscriptionRequest = {
    planSlug?: string | null;
    redirectSuccess?: string | null;
    redirectCancel?: string | null;
};

export type TargetType = 'Unknown' | 'FireBase' | 'DiscordWebhook' | 'Email' | 'WhatsApp';

export type TokenContainer = {
    authToken?: string | null;
};

export type User = {
    id?: string;
    name?: string | null;
    email?: string | null;
    locale?: string | null;
    authProviderId?: string | null;
    createdAt?: string;
    lastSeenAt?: string;
};

export type LoginFirebaseData = {
    body: TokenContainer;
    path?: never;
    query?: never;
    url: '/api/auth/firebase';
};

export type LoginFirebaseErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type LoginFirebaseError = LoginFirebaseErrors[keyof LoginFirebaseErrors];

export type LoginFirebaseResponses = {
    /**
     * OK
     */
    200: TokenContainer;
};

export type LoginFirebaseResponse = LoginFirebaseResponses[keyof LoginFirebaseResponses];

export type GetFiltersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/filters/user';
};

export type GetFiltersErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetFiltersError = GetFiltersErrors[keyof GetFiltersErrors];

export type GetFiltersResponses = {
    /**
     * OK
     */
    200: Array<ListingListener>;
};

export type GetFiltersResponse = GetFiltersResponses[keyof GetFiltersResponses];

export type GetOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/filters/options';
};

export type GetOptionsErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetOptionsError = GetOptionsErrors[keyof GetOptionsErrors];

export type GetOptionsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: FilterOptions;
    };
};

export type GetOptionsResponse = GetOptionsResponses[keyof GetOptionsResponses];

export type ReportMatchData = {
    body?: ResultReport;
    path?: never;
    query?: never;
    url: '/api/filters/report';
};

export type ReportMatchErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type ReportMatchError = ReportMatchErrors[keyof ReportMatchErrors];

export type ReportMatchResponses = {
    /**
     * OK
     */
    200: string;
};

export type ReportMatchResponse = ReportMatchResponses[keyof ReportMatchResponses];

export type AddFilterData = {
    body?: ListingListener;
    path?: never;
    query?: never;
    url: '/api/filters';
};

export type AddFilterErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type AddFilterError = AddFilterErrors[keyof AddFilterErrors];

export type AddFilterResponses = {
    /**
     * OK
     */
    200: ListingListener;
};

export type AddFilterResponse = AddFilterResponses[keyof AddFilterResponses];

export type DeleteFilterData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/filters/{id}';
};

export type DeleteFilterErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type DeleteFilterError = DeleteFilterErrors[keyof DeleteFilterErrors];

export type DeleteFilterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteFilterWithTokenData = {
    body?: never;
    path: {
        id: number;
        token: string;
    };
    query?: never;
    url: '/api/filters/{id}/token/{token}';
};

export type DeleteFilterWithTokenErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type DeleteFilterWithTokenError = DeleteFilterWithTokenErrors[keyof DeleteFilterWithTokenErrors];

export type DeleteFilterWithTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetFilterByTokenData = {
    body?: never;
    path: {
        id: number;
        token: string;
    };
    query?: never;
    url: '/api/filters/{id}/token/{token}';
};

export type GetFilterByTokenErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetFilterByTokenError = GetFilterByTokenErrors[keyof GetFilterByTokenErrors];

export type GetFilterByTokenResponses = {
    /**
     * OK
     */
    200: ListingListener;
};

export type GetFilterByTokenResponse = GetFilterByTokenResponses[keyof GetFilterByTokenResponses];

export type TestFilterData = {
    body?: ListingListener;
    path?: never;
    query?: never;
    url: '/api/filters/test';
};

export type TestFilterErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type TestFilterError = TestFilterErrors[keyof TestFilterErrors];

export type TestFilterResponses = {
    /**
     * OK
     */
    200: Array<StoredListing>;
};

export type TestFilterResponse = TestFilterResponses[keyof TestFilterResponses];

export type GetLocationData = {
    body?: never;
    path: {
        zip: string;
    };
    query?: never;
    url: '/api/location/{zip}';
};

export type GetLocationErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetLocationError = GetLocationErrors[keyof GetLocationErrors];

export type GetLocationResponses = {
    /**
     * OK
     */
    200: DetailedLocation;
};

export type GetLocationResponse = GetLocationResponses[keyof GetLocationResponses];

export type GetCountryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/country';
};

export type GetCountryErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetCountryError = GetCountryErrors[keyof GetCountryErrors];

export type GetCountryResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetCountryResponse = GetCountryResponses[keyof GetCountryResponses];

export type GetFlipsData = {
    body?: never;
    path: {
        category: string;
    };
    query?: {
        limit?: number;
    };
    url: '/api/flips/{category}';
};

export type GetFlipsErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetFlipsError = GetFlipsErrors[keyof GetFlipsErrors];

export type GetFlipsResponses = {
    /**
     * OK
     */
    200: Array<Flip>;
};

export type GetFlipsResponse = GetFlipsResponses[keyof GetFlipsResponses];

export type GetMatchesData = {
    body?: never;
    path?: never;
    query?: {
        before?: string;
        limit?: number;
        after?: string;
    };
    url: '/api/matches';
};

export type GetMatchesErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetMatchesError = GetMatchesErrors[keyof GetMatchesErrors];

export type GetMatchesResponses = {
    /**
     * OK
     */
    200: Array<FilterMatch>;
};

export type GetMatchesResponse = GetMatchesResponses[keyof GetMatchesResponses];

export type GetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/stats';
};

export type GetStatsErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetStatsError = GetStatsErrors[keyof GetStatsErrors];

export type GetStatsResponses = {
    /**
     * OK
     */
    200: MatchStats;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type GetSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/payment/subscription';
};

export type GetSubscriptionErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetSubscriptionError = GetSubscriptionErrors[keyof GetSubscriptionErrors];

export type GetSubscriptionResponses = {
    /**
     * OK
     */
    200: Array<ActiveSubscription>;
};

export type GetSubscriptionResponse = GetSubscriptionResponses[keyof GetSubscriptionResponses];

export type SubscribeData = {
    body?: SubscriptionRequest;
    path?: never;
    query?: never;
    url: '/api/payment/subscription';
};

export type SubscribeErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type SubscribeError = SubscribeErrors[keyof SubscribeErrors];

export type SubscribeResponses = {
    /**
     * OK
     */
    200: string;
};

export type SubscribeResponse = SubscribeResponses[keyof SubscribeResponses];

export type CancelSubscriptionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/payment/subscription/{id}';
};

export type CancelSubscriptionErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type CancelSubscriptionError = CancelSubscriptionErrors[keyof CancelSubscriptionErrors];

export type CancelSubscriptionResponses = {
    /**
     * OK
     */
    200: string;
};

export type CancelSubscriptionResponse = CancelSubscriptionResponses[keyof CancelSubscriptionResponses];

export type GetProductData = {
    body?: never;
    path: {
        /**
         * Product ID
         */
        id: string;
    };
    query?: never;
    url: '/api/Product/{id}';
};

export type GetProductErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetProductError = GetProductErrors[keyof GetProductErrors];

export type GetProductResponses = {
    /**
     * OK
     */
    200: Product;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type GetProductMatchesData = {
    body?: never;
    path: {
        /**
         * Product ID
         */
        id: string;
    };
    query?: {
        /**
         * Cursor timestamp - fetch listings before this time (defaults to current time)
         */
        before?: string;
        /**
         * Number of items to return (default: 50, max: 100)
         */
        limit?: number;
    };
    url: '/api/Product/{id}/matches';
};

export type GetProductMatchesErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetProductMatchesError = GetProductMatchesErrors[keyof GetProductMatchesErrors];

export type GetProductMatchesResponses = {
    /**
     * OK
     */
    200: Array<ProductMatch>;
};

export type GetProductMatchesResponse = GetProductMatchesResponses[keyof GetProductMatchesResponses];

export type ReportProductIssueData = {
    /**
     * Issue report details
     */
    body?: ProductIssueReport;
    path: {
        /**
         * Product ID
         */
        id: string;
    };
    query?: never;
    url: '/api/Product/{id}/report';
};

export type ReportProductIssueErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type ReportProductIssueError = ReportProductIssueErrors[keyof ReportProductIssueErrors];

export type ReportProductIssueResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type IsProductAvailableData = {
    body?: never;
    path: {
        platform: Platform;
        id: string;
    };
    query?: never;
    url: '/api/Product/{platform}/{id}/available';
};

export type IsProductAvailableErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type IsProductAvailableError = IsProductAvailableErrors[keyof IsProductAvailableErrors];

export type IsProductAvailableResponses = {
    /**
     * OK
     */
    200: AvailabilityResult;
};

export type IsProductAvailableResponse = IsProductAvailableResponses[keyof IsProductAvailableResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Product/categories';
};

export type GetCategoriesErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetCategoriesError = GetCategoriesErrors[keyof GetCategoriesErrors];

export type GetCategoriesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type SearchProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search query
         */
        query?: string;
        /**
         * Optional category filter
         */
        category?: string;
        offset?: number;
        /**
         * Maximum results (default 20)
         */
        limit?: number;
    };
    url: '/api/Product/search';
};

export type SearchProductsErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type SearchProductsError = SearchProductsErrors[keyof SearchProductsErrors];

export type SearchProductsResponses = {
    /**
     * OK
     */
    200: SearchProductsResult;
};

export type SearchProductsResponse = SearchProductsResponses[keyof SearchProductsResponses];

export type DoRedirectData = {
    body?: never;
    path?: never;
    query?: {
        url?: string;
    };
    url: '/api/redirect';
};

export type DoRedirectErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type DoRedirectError = DoRedirectErrors[keyof DoRedirectErrors];

export type DoRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/referral/info';
};

export type GetInfoErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetInfoError = GetInfoErrors[keyof GetInfoErrors];

export type GetInfoResponses = {
    /**
     * OK
     */
    200: ReferralInfo;
};

export type GetInfoResponse = GetInfoResponses[keyof GetInfoResponses];

export type CreateLinkData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
        text?: string;
    };
    url: '/api/referral/link';
};

export type CreateLinkErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type CreateLinkError = CreateLinkErrors[keyof CreateLinkErrors];

export type CreateLinkResponses = {
    /**
     * OK
     */
    200: InviteLink;
};

export type CreateLinkResponse = CreateLinkResponses[keyof CreateLinkResponses];

export type ListLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/referral/links';
};

export type ListLinksErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type ListLinksError = ListLinksErrors[keyof ListLinksErrors];

export type ListLinksResponses = {
    /**
     * OK
     */
    200: Array<InviteLink>;
};

export type ListLinksResponse = ListLinksResponses[keyof ListLinksResponses];

export type GetLinkData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/referral/link/{id}';
};

export type GetLinkErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetLinkError = GetLinkErrors[keyof GetLinkErrors];

export type GetLinkResponses = {
    /**
     * OK
     */
    200: InviteLink;
};

export type GetLinkResponse = GetLinkResponses[keyof GetLinkResponses];

export type UseLinkData = {
    body?: never;
    path?: never;
    query?: {
        inviter?: string;
    };
    url: '/api/referral/use';
};

export type UseLinkErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type UseLinkError = UseLinkErrors[keyof UseLinkErrors];

export type UseLinkResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type GetMeErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateMeData = {
    body?: User;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type UpdateMeErrors = {
    /**
     * Bad Request
     */
    400: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * More info about the error, may sometimes be sufficient to display to user
         */
        message?: string;
    };
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: {
        /**
         * Human readable id for this kind of error
         */
        slug?: string;
        /**
         * Unknown error occured
         */
        message?: string;
        /**
         * Id for the error report with this id
         */
        trace?: string;
    };
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    /**
     * OK
     */
    200: User;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];
